import { stylesheet } from 'typestyle';
import { Constants } from '../../utils/Constants';

export const classes = stylesheet({
  messageForm: {
    background: '#fff',
    display: 'flex',
    flex: '0 0 auto',
    flexDirection: 'column',
    maxHeight: '100%',
    position: 'static',
    transitionProperty: 'all',
    width: '100%',
  },
  textEditor: {
    flex: '1 0 auto',
    flexDirection: 'column',
    maxHeight: '100%',
    overflow: 'hidden',
    position: 'relative!important',
    flexGrow: '1!important',
    display: 'flex!important',
  },
  editor: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: '1',
    height: '100%',
    maxHeight: '120px',
    overflow: 'auto',
  },
  editorBox: {
    flex: '1 0 auto',
    position: 'relative!important',
    flexGrow: '1!important',
    display: 'block',
    minHeight: '60px',
    overflow: 'hidden',
    padding: '12px 48px 0 12px',
    fontSize: '13px',
    lineHeight: '1.42857',
    fontWeight: '400',
    border: '0px',
    outline: 'none',
    borderTop: '1.5px solid #ccc',
    $nest: {
      '&:focus': {
        borderTop: '1.5px solid #3b5580',
      },
    },
  },
  textbox: {
    fontSize: '1.4rem',
    lineHeight: '1.42857',
    fontWeight: '400',
    color: 'rgba(0,0,0,.6)',
  },
  btnWrapper: {
    height: '0',
    paddingRight: '12px',
    position: 'absolute',
    right: '0',
  },
  btn: {
    height: '32px',
    width: '32px',
    backgroundColor: 'transparent',
    color: 'rgba(0,0,0,.6)',
    position: 'relative',
    top: '4px',
    right: '0',
    zIndex: '2',
    transitionTimingFunction: 'cubic-bezier(.4,0,.2,1)',
    transitionDuration: '167ms',
    alignItems: 'center',
    border: 'none',
    borderRadius: '2px',
    boxSizing: 'border-box',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontWeight: '600',
    display: 'inline-flex',
    justifyContent: 'center',
    maxWidth: '480px',
    overflow: 'hidden',
    outlineWidth: '2px',
    transitionProperty: 'background-color,box-shadow,color',
    verticalAlign: 'middle',
  },
  footer: {
    backgroundColor: '#f3f6f8',
    borderTop: '1px solid #cdcfd2',
    height: '40px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
    padding: '4px 8px',
  },
  IconsWrapper: {
    display: 'flex!important',
  },
  toolboxItemBtn: {
    height: '32px',
    width: '32px',
    backgroundColor: 'transparent',
    color: 'rgba(0,0,0,.6)',
    borderRadius: '50%',
    padding: '0',
    transitionTimingFunction: 'cubic-bezier(.4,0,.2,1)',
    transitionDuration: '167ms',
    alignItems: 'center',
    border: 'none',
    boxSizing: 'border-box',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontWeight: '600',
    display: 'inline-flex',
    justifyContent: 'center',
    maxWidth: '480px',
    overflow: 'hidden',
    outlineWidth: '2px',
    transitionProperty: 'background-color,box-shadow,color',
    verticalAlign: 'middle',
    fontSize: '12px',
    minHeight: '24px',
    lineHeight: '20px',
  },
  emojiIcon: {
    width: '16px',
    height: '16px',
    color: 'rgba(0,0,0,0.6)',
    margin: '0',
    display: 'inline-block',
    overflow: 'hidden',
    position: 'relative',
  },
  fileIcon: {
    position: 'absolute',
    zIndex: 2000,
    height: 32,
    width: 32,
    opacity: 0,
    cursor: 'pointer',
  },
  btnWrapper: {
    display: 'flex!important',
    alignTtems: 'center!important',
  },
  msgBtn: {
    fontSize: 13,
    transitionTimingFunction: 'cubic-bezier(.4,0,.2,1)',
    transitionDuration: '167ms',
    alignItems: 'center',
    border: 'none',
    borderRadius: '2px',
    boxSizing: 'border-box',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontWeight: 400,
    display: 'inline-flex',
    justifyContent: 'center',
    maxWidth: '480px',
    overflow: 'hidden',
    outlineWidth: '2px',
    transitionProperty: 'background-color,box-shadow,color',
    verticalAlign: 'middle',
    backgroundColor: '#3b5580',
    color: '#fff',
    textDecoration: 'none',
    minHeight: 24,
    minWidth: 50,
  },
  msgBtnDisabled: {
    backgroundColor: '#3b5580',
    opacity: 0.5,
    cursor: 'not-allowed',
  },
});
